name: Test

on:
  push:
    branches: [ master, tox ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        env:
          - DJANGO_VERSION=1.11.29
          - DJANGO_VERSION=2.2.28
          - DJANGO_VERSION=3.2.19
          - DJANGO_VERSION=4.2.1
          - FLASK_VERSION=1.0.4
          - FLASK_VERSION=1.1.4
          # - FLASK_VERSION=2.0.3
          # - FLASK_VERSION=2.1.3
          # - FLASK_VERSION=2.2.5
          - FLASK_VERSION=2.3.2
        exclude:
          - python-version: '3.7'
            env: DJANGO_VERSION=4.2.1
          - python-version: '3.7'
            env: FLASK_VERSION=2.3.2
    steps:

    - name: Check out ${{ github.ref }}
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        export ${{ matrix.env }}
        python -m pip install --upgrade pip setuptools wheel
        pip install --requirement requirements.txt
        ./scripts/install_frameworks.sh
        pip install --editable .
        pip list

    - name: Run Tests
      run: |
        export ${{ matrix.env }}
        pip install tox
        tox -e ${{ matrix.python-version }} run -- -v
