name: Test

on:
  push:
    branches: [ master, tox ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Check out ${{ github.ref }}
      uses: actions/checkout@v3

    - name: Set up Python Versions
      uses: actions/setup-python@v4
      with:
        python-version: |
          3.7
          3.8
          3.9
          3.10
          3.11

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --editable .
        pip list

    - name: Run Tests
      run: |
        pip install tox
        pip list
        tox --colored=yes run-parallel --parallel=auto --parallel-no-spinner --skip-missing-interpreters=false
